### ISSUE TITLE
USER STORY: Create account

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/project-4-story#1]
As a **User** I can **create an account** so that ** I can publish a title to the chapter, add an image and login/logout of my account**.

**Criteria:**

- User submits a valid Username
- User should be able to log in and out once account is created

**Todo:**

- [x] Add logic for account registration.
- [x] Add code and logic for signup/login/logout button in navbar.
- [x] Test registration, login and logout.
