### ISSUE TITLE
USER STORY: Admin page

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/project-4-story#2]
As a **Admin/Author** I can **connect to the admin page** so that ** I can post, edit and delete chapters but also see users proposed titles and images.**

**Criteria:**

- The site administrator can log in and access websites backend.
- Admin/Authors can create, update and delete the chapters.
- Admin/Authors can access users proposed titles and published images.

**Todo:**

- [x] Create super users for the authors.
- [x] Test that admin/authors can create, update and delete chapters.
- [x] Test that admin/authors can create, update and delete comments made by users.
