### ISSUE TITLE
USER STORY: Create Comments

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/project-4-story#4]
As a **Registered User** I can **create a comment** so that **I can propose a title and add a suitable image to the storyline.**

**Criteria:**

- User have to registered and logged in.
- Username should automatically be used as name.
- A form for the user to submit their proposed title and chapter image.

**Todo:**

- [x] Add form to the comment section, with the appropriate fields.
- [x] Create the code for model, make the form publish the right kind of info.
- [x]  Test the completed functionality.
