### ISSUE TITLE
USER STORY: Deploy the Site

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/project-4-story#5]
As a **Developer** I can **deploy this website at an early stage** so that **I can be sure that the project is deployable long before the final stage of the project.**

**Criteria:**

- The project is deployed on Heroku.
- The project uses a third party to handle images (Cloudinary).
- The code must be stored on GitHub for the assessor to grade.
- The project uses a postgresSQL database (elephantSQL).

**Todo:**

- [x] Create a repository on Github from project template (Codeanywhere).
- [x] Open project and install Django.
- [x] Setup environment variables.
- [x] Link project with my Cloudinary account.
- [x] Link ElephantSQL instance to my project.
- [x] Link Github repository with Heroku and deploy the first version.
- [x] Add config vars to the Heroku deployment (secret key, database url, port 8000, etc..).
- [x] Test that the website is deployed correctly on Heroku.
