### ISSUE TITLE
USER STORY: UD Comments

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/project-4-story#6]
As a **User** I can **update & delete my comments** so that ** I can change the picture or title to something else.**

**Criteria:**

- User have to be registered and logged in.
- User should only be able to edit/delete their own comments.

**Todo:**

- [x] Add update Comment view and a new html and css to it.
- [x] Add delete Comment view and a new html and css to it.
- [x] Add authentication and eligibility ifs to access update/delete.
- [x] Test the completed functionality with different accounts.
