### ISSUE TITLE
USER STORY: View Comments

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/project-4-story#7]
As a **User** I can **login and read comments** so that **I can take part and post another proposed title and image.**

**Criteria:**

- Comments are displayed on the leftside as a dropdown flow on the chapter it's posted to.
- The comments are listed from oldest to newest.

**Todo:**

- [x] Create the view code for comments.
- [x] Create a template to render the view for comments.
- [x] Connect the URLs.
- [x] Update the appropriate HTML and CSS to get a user friendly view of comments.
- [x] Test the completed functionality with different accounts.
